In [51]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [52]:
df= pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [53]:
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin', 'SibSp', 'Embarked', 'Parch'], axis=1, inplace=True)

In [54]:
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [55]:
target = df['Survived']
inputs= df.drop('Survived', axis='columns')

In [56]:
inputs['Sex']= LabelEncoder().fit_transform(inputs['Sex'])
inputs.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [57]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [58]:
inputs['Age'].fillna(inputs['Age'].mean(), inplace=True)

C:\Users\Niloy\AppData\Local\Temp\ipykernel_38220\3890281895.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  inputs['Age'].fillna(inputs['Age'].mean(), inplace=True)

In [59]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [60]:
x_train, x_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((712, 4), (179, 4), (712,), (179,))

In [61]:
x_train.head()
y_train.head()

298    1
829    1
227    0
858    1
666    0
Name: Survived, dtype: int64

In [62]:
titanic_model = GaussianNB()
titanic_model.fit(x_train, y_train)

GaussianNB()

In [63]:
titanic_model.predict([[22, 1, 0, 7.25]])

c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([1])

In [64]:
titanic_model.score(x_test, y_test)

0.7821229050279329

In [65]:
x_test.head()

     Pclass  Sex        Age     Fare
830       3    0  15.000000  14.4542
877       3    1  19.000000   7.8958
806       1    1  39.000000   0.0000
533       3    0  29.699118  22.3583
850       3    1   4.000000  31.2750

In [66]:
y_test.head()

830    1
877    0
806    0
533    1
850    0
Name: Survived, dtype: int64

In [68]:
df1= pd.read_csv("Spam.csv")
df1.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [69]:
df1.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [70]:
df1['spam'] = df1['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df1.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [71]:
X_train, X_test, Y_train, Y_test = train_test_split(df1['Message'], df1['spam'], test_size=0.25)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((4179,), (1393,), (4179,), (1393,))

In [72]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train_cv = cv.fit_transform(X_train)
X_train_cv.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3, 7527))

In [73]:
from sklearn.naive_bayes import MultinomialNB
spam_model = MultinomialNB()
spam_model.fit(X_train_cv, Y_train)

MultinomialNB()

In [75]:
emails= ['Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!']
emails_count = cv.transform(emails)
spam_model.predict(emails_count)

array([0, 1])

In [76]:
X_test_count = cv.transform(X_test)
spam_model.score(X_test_count, Y_test)

0.9892318736539842

In [77]:
from sklearn.pipeline import Pipeline
spam_pipeline = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('NBv', MultinomialNB())
])

In [78]:
spam_pipeline.fit(X_train, Y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('NBv', MultinomialNB())])

In [80]:
spam_pipeline.predict(emails)

array([0, 1])

In [79]:
spam_pipeline.score(X_test, Y_test)

0.9892318736539842

In [87]:
from sklearn.datasets import load_wine
wine= load_wine()
wine_df = pd.DataFrame(data=wine.data, columns=wine.feature_names)
wine_df.head()
wine_df['target'] = wine.target
wine_df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [88]:
xx= wine_df.drop('target', axis='columns')
yy= wine_df['target']

In [89]:
xx_train, xx_test, yy_train, yy_test = train_test_split(xx, yy, test_size=0.2)
xx_train.shape, xx_test.shape, yy_train.shape, yy_test.shape

((142, 13), (36, 13), (142,), (36,))

In [92]:
wine_model_guassian = GaussianNB()
wine_model_guassian.fit(xx_train, yy_train)
wine_model_guassian.predict([[13.5, 2.5, 2.0, 20.0, 100.0, 2.5, 2.0, 0.3, 1.0, 3.0, 1.0, 3.0, 1000]])

c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([0])

In [94]:
wine_model_guassian.score(xx_test, yy_test)

0.9444444444444444

In [95]:
wine_model_multinomial = MultinomialNB()
wine_model_multinomial.fit(xx_train, yy_train)
wine_model_multinomial.predict([[13.5, 2.5, 2.0, 20.0, 100.0, 2.5, 2.0, 0.3, 1.0, 3.0, 1.0, 3.0, 1000]])

c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array([0])

In [96]:
wine_model_multinomial.score(xx_test, yy_test)

0.7777777777777778