In [337]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.linear_model import Ridge

In [338]:
import warnings
warnings.filterwarnings('ignore')

In [339]:
df= pd.read_csv('Melbourne_housing_FULL.csv')
df.shape

(34857, 21)

In [340]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [341]:
df.shape

(34857, 21)

In [342]:
df1= df[['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount', 
               'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']]
df1.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,SS,Jellis,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,126.0,NaN,NaN
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,NaN,1480000.0
2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0,1035000.0
3,Abbotsford,3,u,VB,Rounds,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,0.0,NaN,NaN
4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0,1465000.0

In [343]:
df1.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        3
Distance             1
CouncilArea          3
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [344]:
df1[['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']]= df1[['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']].fillna(0)
df1.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        0
Distance             0
CouncilArea          3
Bedroom2             0
Bathroom             0
Car                  0
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [345]:
df1[['Landsize', 'BuildingArea']]= df1[['Landsize', 'BuildingArea']].fillna(df1[['Landsize', 'BuildingArea']].mean())
df1.isnull().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          3
Propertycount       0
Distance            0
CouncilArea         3
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price            7610
dtype: int64

In [346]:
df1.dropna(inplace=True)
df1.isnull().sum()

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
dtype: int64

In [347]:
df1.shape

(27244, 15)

In [348]:
df1.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,160.2564,1480000.0
2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0000,1035000.0
4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0000,1465000.0
5,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.0,160.2564,850000.0
6,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.0,142.0000,1600000.0

In [349]:
df1.shape

(27244, 15)

In [350]:
df1['Suburb']= LabelEncoder().fit_transform(df1['Suburb'])
df1['Type']= LabelEncoder().fit_transform(df1['Type'])
df1['Method']= LabelEncoder().fit_transform(df1['Method'])
df1['SellerG']= LabelEncoder().fit_transform(df1['SellerG'])
df1['Regionname']= LabelEncoder().fit_transform(df1['Regionname'])
df1['CouncilArea']= LabelEncoder().fit_transform(df1['CouncilArea'])
df1.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
1,0,2,0,1,32,2,4019.0,2.5,31,2.0,1.0,1.0,202.0,160.2564,1480000.0
2,0,2,0,1,32,2,4019.0,2.5,31,2.0,1.0,0.0,156.0,79.0000,1035000.0
4,0,3,0,3,32,2,4019.0,2.5,31,3.0,2.0,0.0,134.0,150.0000,1465000.0
5,0,3,0,0,32,2,4019.0,2.5,31,3.0,2.0,1.0,94.0,160.2564,850000.0
6,0,4,0,4,206,2,4019.0,2.5,31,3.0,1.0,2.0,120.0,142.0000,1600000.0

In [351]:
x= df1.drop('Price', axis=1)
y= df1['Price']

In [352]:
train_x, test_x, train_y, test_y= train_test_split(x, y, test_size=0.3)
train_x.shape, test_x.shape, train_y.shape, test_y.shape

((19070, 14), (8174, 14), (19070,), (8174,))

In [353]:
hmodel= LinearRegression()
hmodel.fit(train_x, train_y)

LinearRegression()

In [354]:
hmodel.score(test_x, test_y)

0.4247692422597723

In [355]:
hmodel.score(train_x, train_y)

0.4343310488241988

In [356]:
lassoreg= linear_model.Lasso(alpha=50, max_iter=1000, tol=0.01) 
lassoreg.fit(train_x, train_y)

Lasso(alpha=50, tol=0.01)

In [357]:
lassoreg.score(test_x, test_y)

0.4247528988113599

In [358]:
lassoreg.score(train_x, train_y)

0.4343309296072503

In [359]:
ridgereg= Ridge(alpha=50, max_iter=1000, tol=0.01)
ridgereg.fit(train_x, train_y)

Ridge(alpha=50, max_iter=1000, tol=0.01)

In [360]:
ridgereg.score(test_x, test_y)

0.4246151904338348

In [361]:
ridgereg.score(train_x, train_y)

0.43432160356723604