In [60]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC

In [26]:
df= pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [27]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [28]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [29]:
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [30]:
x= df.drop("Outcome", axis=1)
y= df["Outcome"]

In [31]:
scaler= StandardScaler()
x_scaled= scaler.fit_transform(x)
x_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]], shape=(768, 8))

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2,stratify=y, random_state=10)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [33]:
scores= cross_val_score(DecisionTreeClassifier(), x_train, y_train, cv=5)
scores

array([0.73170732, 0.63414634, 0.76422764, 0.64227642, 0.69672131])

In [34]:
scores.mean()

np.float64(0.6938158070105291)

In [35]:
bag_model= BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100,oob_score=True, max_samples=0.8, random_state=0)
bag_model.fit(x_train, y_train)
bag_model.oob_score_

0.760586319218241

In [36]:
bag_model= BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100,oob_score=True, max_samples=0.8, random_state=0)
scores1= cross_val_score(bag_model, x_train, y_train, cv=5).mean()
scores1

np.float64(0.7605890976942556)

In [37]:
scoresrdf= cross_val_score(RandomForestClassifier(), x_train, y_train, cv=5).mean()
scoresrdf

np.float64(0.7426895908303345)

In [38]:
df1= pd.read_csv("heart.csv")
df1.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [39]:
df1.shape

(918, 12)

In [40]:
df1.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [41]:
df1[df1.Cholesterol>(df1.Cholesterol.mean()+3*df1.Cholesterol.std())]
df1.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [42]:
df1.shape

(918, 12)

In [43]:

df2 = df1[df1.Cholesterol<=(df1.Cholesterol.mean()+3*df1.Cholesterol.std())]
df2.shape

(915, 12)

In [44]:

df1[df1.MaxHR>(df1.MaxHR.mean()+3*df1.MaxHR.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [45]:
df1[df1.Oldpeak>(df1.Oldpeak.mean()+3*df1.Oldpeak.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
166,50,M,ASY,140,231,0,ST,140,Y,5.0,Flat,1
702,59,M,TA,178,270,0,LVH,145,N,4.2,Down,0
771,55,M,ASY,140,217,0,Normal,111,Y,5.6,Down,1
791,51,M,ASY,140,298,0,Normal,122,Y,4.2,Flat,1
850,62,F,ASY,160,164,0,LVH,145,N,6.2,Down,1
900,58,M,ASY,114,318,0,ST,140,N,4.4,Down,1

In [46]:

df3 = df2[df2.Oldpeak<=(df2.Oldpeak.mean()+3*df2.Oldpeak.std())]
df3.shape

(909, 12)

In [47]:
df1[df1.RestingBP>(df1.RestingBP.mean()+3*df1.RestingBP.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
109,39,M,ATA,190,241,0,Normal,106,N,0.0,Up,0
241,54,M,ASY,200,198,0,Normal,142,Y,2.0,Flat,1
365,64,F,ASY,200,0,0,Normal,140,Y,1.0,Flat,1
399,61,M,NAP,200,0,1,ST,70,N,0.0,Flat,1
592,61,M,ASY,190,287,1,LVH,150,Y,2.0,Down,1
732,56,F,ASY,200,288,1,LVH,133,Y,4.0,Down,1
759,54,M,ATA,192,283,0,LVH,195,N,0.0,Up,1

In [48]:
df4 = df3[df3.RestingBP<=(df3.RestingBP.mean()+3*df3.RestingBP.std())]
df4.shape

(902, 12)

In [55]:
le= LabelEncoder()
df4.Sex= le.fit_transform(df4.Sex)
df4.RestingECG= le.fit_transform(df4.RestingECG)
df4.ExerciseAngina= le.fit_transform(df4.ExerciseAngina)
df4.HeartDisease= le.fit_transform(df4.HeartDisease)
df4.ChestPainType= le.fit_transform(df4.ChestPainType)
df4.ST_Slope= le.fit_transform(df4.ST_Slope)
df4.head()

C:\Users\Niloy\AppData\Local\Temp\ipykernel_14624\4021590049.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.Sex= le.fit_transform(df4.Sex)
C:\Users\Niloy\AppData\Local\Temp\ipykernel_14624\4021590049.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.RestingECG= le.fit_transform(df4.RestingECG)
C:\Users\Niloy\AppData\Local\Temp\ipykernel_14624\4021590049.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.ExerciseAngina= le.fit_transform(df4.ExerciseAngina)
C:\Users\Niloy\AppData\Local\Temp\ipykernel_14624\4021590049.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.HeartDisease= le.fit_transform(df4.HeartDisease)
C:\Users\Niloy\AppData\Local\Temp\ipykernel_14624\4021590049.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.ChestPainType= le.fit_transform(df4.ChestPainType)
C:\Users\Niloy\AppData\Local\Temp\ipykernel_14624\4021590049.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.ST_Slope= le.fit_transform(df4.ST_Slope)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [56]:
X= df4.drop("HeartDisease", axis=1)
Y= df4["HeartDisease"]

In [59]:
hscaler= StandardScaler()
X_scaled= hscaler.fit_transform(X)
X_scaled

array([[-1.42896269,  0.51485643,  0.22498958, ..., -0.82065181,
        -0.84676261,  1.0456339 ],
       [-0.47545956, -1.94228905,  1.27107517, ..., -0.82065181,
         0.14079864, -0.62072967],
       [-1.74679706,  0.51485643,  0.22498958, ..., -0.82065181,
        -0.84676261,  1.0456339 ],
       ...,
       [ 0.37209878,  0.51485643, -0.82109601, ...,  1.21854359,
         0.33831089, -0.62072967],
       [ 0.37209878, -1.94228905,  0.22498958, ..., -0.82065181,
        -0.84676261, -0.62072967],
       [-1.64085227,  0.51485643,  1.27107517, ..., -0.82065181,
        -0.84676261,  1.0456339 ]], shape=(902, 11))

In [58]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, stratify=Y, random_state=10)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((721, 11), (181, 11), (721,), (181,))

In [64]:
hsvcscores= cross_val_score(SVC(), X_train, Y_train, cv=5)
hsvcscores.mean()

np.float64(0.8571551724137931)

In [65]:
svc_bag= BaggingClassifier(estimator=SVC(), n_estimators=100, oob_score=True, max_samples=0.8, random_state=0)
svc_bag.fit(X_train, Y_train)
svc_bag.oob_score_

0.8654646324549237

In [67]:
hdstScores= cross_val_score(DecisionTreeClassifier(), X_train, Y_train, cv=5)
hdstScores.mean()

np.float64(0.7947605363984674)

In [68]:
dst_bag= BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100, oob_score=True, max_samples=0.8, random_state=0)
dst_bag.fit(X_train, Y_train)
dst_bag.oob_score_

0.8613037447988904